package exercício01;

import java.util.Random;

public class Principal {

	public static void main(String[] args) {
		
		Random gerar=new Random();
		boolean perg=gerar.nextBoolean();
		
		String[][] perg1= {
		{"1. De quem é a famosa frase “Penso, logo existo”?",
				"\na) Platão",
				"\nb) Galileu Galilei" ,
				"\nc) Descartes," ,
				"\nd) Sócrates" ,
				"\ne) Francis Bacon"},
		{"2. Quais o menor e o maior país do mundo?",
				"\na) Vaticsano e Rússia",
				"\nb) Nauru e China",
				"\nc) Mônaco e Canadá",
				"\nd) Malta e Estados Unidos",
				"\ne) São Marino e Índia"},
		{"3. Qual o nome do presidente do Brasil que ficou conhecido como Jango?",
				"\na) Jânio Quadros",
				"\nb) Jacinto Anjos",
				"\nc) Getúlio Vargas",
				"\nd) João Figueiredo",
				"\ne) João Goulart"},
		{"4. Qual o grupo em que todas as palavras foram escritas corretamente?",
				"\na) Asterístico, beneficiente, meteorologia, entertido",
				"\nb) Asterisco, beneficente, meteorologia, entretido",
				"\nc) Asterisco, beneficente, metereologia, entretido",
				"\nd) Asterístico, beneficiente, metereologia, entretido",
				"\ne) Asterisco, beneficiente, metereologia, entretido"},
		{"5. Quantas casas decimais tem o número pi?",
				"\na) Duas",
				"\nb) Centenas",
				"\nc) Trilhares",
				"\nd) Vinte",
				"\ne) Milhares"},
		{"6. Quais os países que têm a maior e a menor expectativa de vida do mundo?",
				"\na) Japão e Serra Leoa",
				"\nb) Austrália e Afeganistão",
				"\nc) Itália e Chade",
				"\nd) Brasil e Congo",
				"\ne) Estados Unidos e Angola"},
		{"7. Qual o número mínimo de jogadores numa partida de futebol?",
				"\na) 8",
				"\nb) 10",
				"\nc) 9",
				"\nd) 5",
		        "\ne) 7"},
		{"8. Quais as duas datas que são comemoradas em novembro?",
				"\na) Independência do Brasil e Dia da Bandeira",
		        "\nb) Proclamação da República e Dia Nacional da Consciência Negra",
				"\nc) Dia do Médico e Dia de São Lucas",
				"\nd) Dia de Finados e Dia Nacional do Livro",
				"\ne) Black Friday e Dia da Árvore"},
		{"9. Quanto tempo a luz do Sol demora para chegar à Terra?",
				"\na) 12 minutos",
				"\nb) 1 dia",
				"\nc) 12 horas",
		        "\nd) 8 minutos",
				"\ne) segundos"},
		{"10. Quais são os três predadores do reino animal reconhecidos pela habilidade de caçar em grupo, se camuflar para surpreender as presas e possuir sentidos apurados, respectivamente:",  
				"\na) Tubarão branco, crocodilo e sucuri",
				"\nb) Tigre, gavião e orca",
				"\nc) Hiena, urso branco e lobo cinzento",
				"\nd) Orca, onça e tarântula" ,
				"\ne) Leão, tubarão branco e urso cinzento" },
		{"11. Em que período da pré-história o fogo foi descoberto?" ,
				"\na) Neolítico" ,
				"\nb) Paleolítico" ,
				"\nc) Idade dos Metais" ,
				"\nd) Período da Pedra Polida" ,
				"\ne) Idade Média"},
		{"12. Qual a montanha mais alta do Brasil?",
				"\na) Pico da Neblina",
				"\nb) Pico Paraná",
				"\nc) Monte Roraima",
				"\nd) Pico Maior de Friburgo",
				"\ne) Pico da Bandeira"},
		{"13. Qual a velocidade da luz?",
				"\na) 300 000 000 metros por segundo (m/s)",
				"\nb) 150 000 000 metros por segundo (m/s)",
				"\nc) 199 792 458 metros por segundo (m/s)",
		        "\nd) 299 792 458 metros por segundo (m/s)",
				"\ne) 30 000 000 metros por segundo (m/s)"},
		{"14. Em qual local da Ásia o português é língua oficial?",
				"\na) Índia",
				"\nb) Filipinas",
				"\nc) Moçambique",
		        "\nd) Macau",
				"\ne) Portugal"},
		{"15. Quais destas construções famosas ficam nos Estados Unidos?",
				"\na) Estátua da Liberdade, Golden Gate Bridge e Empire State Building",
				"\nb) Estátua da Liberdade, Big Ben e The High Line",
				"\nc) Angkor Wat, Taj Mahal e Skywalk no Grand Canyon",
				"\nd) Lincoln Memorial, Sidney Opera House e Burj Khalifa",
				"\ne) 30 St Mary Axe, The High Line e Residencial 148 Spruce Street"},
		};
		
		
		
	}

}
